services:
  accounts:
      image: divyaparihar/accounts:latest
      ports:
        - "8081:8081"
      networks:
        - bank-network
  card:
      image: divyaparihar/card:latest
      ports: 
        - "8082:8082"
      networks: 
        - bank-network
  loans:
      image: divyaparihar/card:latest
      ports: 
        - "8083:8083"
      networks: 
        - bank-network 
  insurance:
      image: divyaparihar/insurance:latest
      ports: 
        - "8085:8085"
      networks: 
        - bank-network 
  configserver:
      image: divyaparihar/card:latest
      ports: 
        - "8075:8075"
      networks: 
        - bank-network          
networks:
  bank-network: {}